# @package _global_

num_workers: 5

model_name: simpletransformer

simpletransformer:
  hidden:
    meg: 320
  depth: 4
  nhead: 8
  subject_layers: false
  positional_embedding: false

optim:
  loss: clip
  epochs: 200
  max_batches: 1200
  batch_size: 256

norm:
  clip: true

task:
  type: decode
  # Moves the MEG signal to the 'past' by given ms value. This allows training
  # causal models with better alignment between brain signals and the presented
  # features.
  offset_meg_ms: 150