# @package _global_

num_workers: 5

model_name: timesnet

timesnet:
  hidden:
    meg: 320
  depth: 2
  subject_layers: false
  merger: false
  merger_pos_dim: 2048
  sequence_lenth: 361  
  num_kernels: 6
  top_k: 3
  dropout_projection: 0.3
  d_model: 32
  d_ff: 32
  flatten_out_channels: 1024
  enc_embedding: true

optim:
  loss: clip
  epochs: 200
  max_batches: 1200
  batch_size: 256

norm:
  clip: true

task:
  type: decode
  # Moves the MEG signal to the 'past' by given ms value. This allows training
  # causal models with better alignment between brain signals and the presented
  # features.
  offset_meg_ms: 150